name: build
on: push

env:
  DOTNET_NOLOGO: true
  MSBUILDDISABLENODEREUSE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.1.20452.10
      - run: dotnet build